swagger: '2.0'
info:
  title: test-api
  x-ibm-name: test-api
  version: 1.0.0
schemes:
  - https
basePath: /test-api
security:
  - {}
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: ($httpVerb() = 'GET' and $operationPath() = '/test')
              execute:
                - gatewayscript:
                    version: 2.0.0
                    title: gws-respond-test
                    source: |
                      context.set('message.body','{"msg":"Hello test!"}');
            - condition: ($httpVerb() = 'GET' and $operationPath() = '/test-public')
              execute:
                - gatewayscript:
                    version: 2.0.0
                    title: gws-respond-test-public
                    source: >
                      context.set('message.body','{"msg":"Hello
                      test-public!"}');
            - condition: ($httpVerb() = 'GET' and $operationPath() = '/test-error')
              execute:
                - gatewayscript:
                    version: 2.0.0
                    title: gws-respond-error
                    source: |
                      throw "Something wrong happend."
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
paths:
  /test-error:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
  /test:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      security:
        - clientID: []
      consumes: []
      produces: []
  /test-public:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
